# Generated by Django 5.2.3 on 2025-06-30 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avalia',
            fields=[
                ('id_avalia', models.AutoField(primary_key=True, serialize=False)),
                ('valor_avalia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nome_perfil', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('matricula_perfil', models.CharField(max_length=255)),
                ('foto_perfil', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id_postagem', models.AutoField(primary_key=True, serialize=False)),
                ('autor_postagem', models.CharField(max_length=255)),
                ('data_postagem', models.DateTimeField()),
                ('titulo_postagem', models.CharField(max_length=255)),
                ('conteudo_postagem', models.TextField()),
                ('id_avalia', models.ForeignKey(blank=True, db_column='id_avalia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='socialapp.avalia')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_post',
            fields=[
                ('id_perfil_post', models.AutoField(primary_key=True, serialize=False)),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.DO_NOTHING, to='socialapp.perfil')),
                ('id_postagem', models.ForeignKey(db_column='id_postagem', on_delete=django.db.models.deletion.DO_NOTHING, to='socialapp.postagem')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id_telefone', models.AutoField(primary_key=True, serialize=False)),
                ('numero_telefone', models.CharField(max_length=255)),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.DO_NOTHING, to='socialapp.perfil')),
            ],
        ),
    ]
